version: "3.9"

services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/db.sqlite
      - OPENAI_BASE_URL=https://kurim.ithope.eu/v1
      - OPENAI_API_KEY=sk-4cv4dSfPAv3YxI2jh...
      - MODEL_NAME=gemma3:27b
    restart: unless-stopped

volumes:
  db_data:
